export declare enum ConfigTypes {
    AIRDROP = "aki-airdrop",
    BOT = "aki-bot",
    PMC = "aki-pmc",
    CORE = "aki-core",
    HEALTH = "aki-health",
    HIDEOUT = "aki-hideout",
    HTTP = "aki-http",
    IN_RAID = "aki-inraid",
    INSURANCE = "aki-insurance",
    INVENTORY = "aki-inventory",
    ITEM = "aki-item",
    LOCALE = "aki-locale",
    LOCATION = "aki-location",
    LOOT = "aki-loot",
    MATCH = "aki-match",
    PLAYERSCAV = "aki-playerscav",
    PMC_CHAT_RESPONSE = "aki-pmcchatresponse",
    QUEST = "aki-quest",
    RAGFAIR = "aki-ragfair",
    REPAIR = "aki-repair",
    SCAVCASE = "aki-scavcase",
    TRADER = "aki-trader",
    WEATHER = "aki-weather",
    SEASONAL_EVENT = "aki-seasonalevents",
    LOST_ON_DEATH = "aki-lostondeath",
    GIFTS = "aki-gifts"
}
